import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '@/theme/tokens';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bgPrimary },
  listContent: { paddingBottom: 130 },

  hero: {
    margin: spacing.sm,
    borderRadius: radius.xl,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  heroIcon: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  heroTitle: { color: '#ffffff', fontSize: 23, fontWeight: '900', letterSpacing: -0.4 },
  heroSub: { color: 'rgba(255,255,255,0.78)', fontSize: 11.5, marginTop: 3 },
  addFab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 44,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#ffffff',
  },
  addFabText: { color: '#4f46e5', fontWeight: '900', fontSize: 13 },

  statsRow: { flexDirection: 'row', gap: 8, paddingHorizontal: spacing.sm, marginBottom: 4 },
  statCard: {
    flex: 1,
    borderRadius: radius.md,
    padding: 11,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  statValue: { color: colors.textPrimary, fontSize: 18, fontWeight: '900' },
  statLabel: { color: colors.textMuted, fontSize: 10, fontWeight: '700', marginTop: 2, textTransform: 'uppercase', letterSpacing: 0.4 },
  statDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 7 },

  branchRow: { paddingHorizontal: spacing.sm, gap: 7, paddingVertical: 8 },
  branchChip: {
    height: 34,
    paddingHorizontal: 13,
    borderRadius: 11,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  branchChipOn: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
  branchText: { color: colors.textMuted, fontWeight: '700', fontSize: 11 },
  branchTextOn: { color: '#ffffff' },

  searchRow: {
    marginHorizontal: spacing.sm,
    marginTop: 2,
    marginBottom: 8,
    minHeight: 48,
    paddingHorizontal: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  searchInput: { flex: 1, color: colors.textPrimary, fontSize: 13, paddingVertical: 10 },

  filterRow: { flexDirection: 'row', gap: 7, paddingHorizontal: spacing.sm, marginBottom: 8 },
  filterChip: {
    paddingHorizontal: 12,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  filterChipOn: { backgroundColor: colors.accentSoft, borderColor: colors.borderAccent },
  filterChipText: { color: colors.textMuted, fontWeight: '700', fontSize: 11 },
  filterChipTextOn: { color: colors.accentPrimary },

  errorBox: {
    marginHorizontal: spacing.sm,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  errorText: { flex: 1, color: colors.statusError, fontSize: 12 },
  retry: { color: colors.statusError, fontWeight: '800', fontSize: 12 },

  empty: { alignItems: 'center', padding: 42 },
  emptyTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: '800', marginTop: 12 },
  emptyText: { color: colors.textMuted, fontSize: 12, marginTop: 4, textAlign: 'center' },
  footerHint: {
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
    paddingVertical: 14,
  },

  orderCard: {
    marginHorizontal: spacing.sm,
    marginBottom: 10,
    borderRadius: radius.lg,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderLeftWidth: 4,
    overflow: 'hidden',
  },
  orderHead: { flexDirection: 'row', padding: 13, gap: 10 },
  orderIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  orderNo: { color: colors.textPrimary, fontSize: 15, fontWeight: '800' },
  orderMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  orderTotal: { color: colors.accentPrimary, fontSize: 15, fontWeight: '900' },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: '#f8fafc',
  },
  statusText: { fontSize: 10, fontWeight: '800', textTransform: 'capitalize' },

  summaryStrip: {
    marginHorizontal: 12,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  countBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
  },
  countBadgeText: { color: colors.textSecondary, fontWeight: '800', fontSize: 11 },

  itemsWrap: {
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    padding: 10,
    gap: 8,
    backgroundColor: colors.bgTertiary,
  },
  itemCard: {
    padding: 11,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  itemName: { color: colors.textPrimary, fontSize: 13, fontWeight: '800' },
  itemMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  serials: { color: colors.accentPrimary, fontSize: 10, marginTop: 4, fontFamily: 'monospace' },
  itemFooter: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  itemActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end' },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 9,
    backgroundColor: colors.accentPrimary,
  },
  returnBtn: { backgroundColor: '#d97706' },
  viewBtn: { backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: colors.borderAccent },
  actionText: { color: '#ffffff', fontSize: 11, fontWeight: '800' },

  modalRoot: { flex: 1, backgroundColor: colors.bgPrimary, paddingTop: 48 },
  modalHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  modalTitle: { color: colors.textPrimary, fontSize: 20, fontWeight: '900' },
  modalSub: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgTertiary,
  },
  sectionLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  input: {
    minHeight: 46,
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    justifyContent: 'center',
    color: colors.textPrimary,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  selectedBox: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    marginBottom: 8,
  },
  selectedName: { color: colors.textPrimary, fontWeight: '800', fontSize: 14 },
  selectedMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  link: { color: colors.accentPrimary, fontWeight: '800', fontSize: 12, marginTop: 6 },
  pickRow: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pickRowOn: { borderColor: colors.accentPrimary, backgroundColor: colors.accentSoft },
  pickName: { color: colors.textPrimary, fontWeight: '700', fontSize: 13 },
  pickMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  pickPrice: { color: colors.accentPrimary, fontWeight: '900', fontSize: 13 },
  cartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: 7,
  },
  priceMini: {
    width: 72,
    height: 36,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingHorizontal: 8,
    color: colors.textPrimary,
    fontWeight: '700',
    backgroundColor: colors.bgTertiary,
  },
  qtyBtns: { flexDirection: 'row', gap: 6 },
  qtyBtnText: {
    width: 28,
    height: 28,
    textAlign: 'center',
    lineHeight: 26,
    borderRadius: 8,
    backgroundColor: colors.bgTertiary,
    color: colors.textPrimary,
    fontWeight: '800',
    overflow: 'hidden',
  },
  modalFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 14,
    paddingBottom: 28,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15,23,42,0.55)',
  },
  sheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingBottom: 28,
  },
  summaryBox: {
    marginTop: 10,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
  },
  returnIconWrap: {
    alignSelf: 'center',
    width: 64,
    height: 64,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(217,119,6,0.12)',
    borderWidth: 2,
    borderColor: 'rgba(217,119,6,0.25)',
    marginBottom: 14,
  },
  returnAmountBox: {
    marginTop: 14,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: 'rgba(217,119,6,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(217,119,6,0.22)',
  },
  dangerBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#d97706',
  },
  dangerBtnText: { color: '#ffffff', fontWeight: '800', fontSize: 14 },
  ghostBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  ghostBtnText: { color: colors.textSecondary, fontWeight: '800', fontSize: 14 },
});
