import { StyleSheet } from 'react-native';
import { colors, radius, shadows, spacing } from '@/theme/tokens';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bgPrimary },
  listContent: { paddingBottom: 130 },

  hero: {
    margin: spacing.sm,
    borderRadius: radius.xl,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  heroIcon: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  heroTitle: { color: '#ffffff', fontSize: 23, fontWeight: '900', letterSpacing: -0.4 },
  heroSub: { color: 'rgba(255,255,255,0.78)', fontSize: 11.5, marginTop: 3 },
  addFab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 44,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#ffffff',
  },
  addFabText: { color: '#4f46e5', fontWeight: '900', fontSize: 13 },

  statsRow: { flexDirection: 'row', gap: 8, paddingHorizontal: spacing.sm, marginBottom: 4 },
  statCard: {
    flex: 1,
    borderRadius: radius.md,
    padding: 11,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  statValue: { color: colors.textPrimary, fontSize: 18, fontWeight: '900' },
  statLabel: { color: colors.textMuted, fontSize: 10, fontWeight: '700', marginTop: 2, textTransform: 'uppercase', letterSpacing: 0.4 },
  statDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 7 },

  branchRow: { paddingHorizontal: spacing.sm, gap: 7, paddingVertical: 8 },
  branchChip: {
    height: 34,
    paddingHorizontal: 13,
    borderRadius: 11,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  branchChipOn: { backgroundColor: colors.accentPrimary, borderColor: colors.accentPrimary },
  branchText: { color: colors.textMuted, fontWeight: '700', fontSize: 11 },
  branchTextOn: { color: '#ffffff' },

  searchRow: {
    marginHorizontal: spacing.sm,
    marginTop: 2,
    marginBottom: 8,
    minHeight: 48,
    paddingHorizontal: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  searchInput: { flex: 1, color: colors.textPrimary, fontSize: 13, paddingVertical: 10 },

  filterRow: { flexDirection: 'row', gap: 7, paddingHorizontal: spacing.sm, marginBottom: 8 },
  filterChip: {
    paddingHorizontal: 12,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  filterChipOn: { backgroundColor: colors.accentSoft, borderColor: colors.borderAccent },
  filterChipText: { color: colors.textMuted, fontWeight: '700', fontSize: 11 },
  filterChipTextOn: { color: colors.accentPrimary },

  errorBox: {
    marginHorizontal: spacing.sm,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  errorText: { flex: 1, color: colors.statusError, fontSize: 12 },
  retry: { color: colors.statusError, fontWeight: '800', fontSize: 12 },

  empty: { alignItems: 'center', padding: 42 },
  emptyTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: '800', marginTop: 12 },
  emptyText: { color: colors.textMuted, fontSize: 12, marginTop: 4, textAlign: 'center' },
  footerHint: {
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
    paddingVertical: 14,
  },

  orderCard: {
    marginHorizontal: spacing.sm,
    marginBottom: 10,
    borderRadius: radius.lg,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderLeftWidth: 4,
    overflow: 'hidden',
  },
  orderHead: { flexDirection: 'row', padding: 13, gap: 10 },
  orderIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  orderNo: { color: colors.textPrimary, fontSize: 15, fontWeight: '800' },
  orderMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  orderTotal: { color: colors.accentPrimary, fontSize: 15, fontWeight: '900' },
  statusPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    backgroundColor: '#f8fafc',
  },
  statusText: { fontSize: 10, fontWeight: '800', textTransform: 'capitalize' },

  summaryStrip: {
    marginHorizontal: 12,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  countBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e2e8f0',
  },
  countBadgeText: { color: colors.textSecondary, fontWeight: '800', fontSize: 11 },

  itemsWrap: {
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    padding: 10,
    gap: 8,
    backgroundColor: colors.bgTertiary,
  },
  itemCard: {
    padding: 11,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  itemName: { color: colors.textPrimary, fontSize: 13, fontWeight: '800' },
  itemMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  serials: { color: colors.accentPrimary, fontSize: 10, marginTop: 4, fontFamily: 'monospace' },
  itemFooter: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  itemActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, justifyContent: 'flex-end' },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 9,
    backgroundColor: colors.accentPrimary,
  },
  returnBtn: { backgroundColor: '#d97706' },
  viewBtn: { backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: colors.borderAccent },
  actionText: { color: '#ffffff', fontSize: 11, fontWeight: '800' },

  modalRoot: { flex: 1, backgroundColor: colors.bgPrimary, paddingTop: 48 },
  modalHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingBottom: 10,
  },
  modalTitle: { color: colors.textPrimary, fontSize: 20, fontWeight: '900' },
  modalSub: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgTertiary,
  },
  sectionLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  input: {
    minHeight: 46,
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 8,
    justifyContent: 'center',
    color: colors.textPrimary,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  productSearchBar: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingLeft: 13,
    paddingRight: 5,
    borderRadius: 15,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  retailerSearchBar: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderRadius: 13,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  assignRetailerIntro: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    padding: 13,
    marginBottom: 12,
    borderRadius: 15,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  assignRetailerIntroIcon: {
    width: 43,
    height: 43,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  assignRetailerIntroTitle: { color: colors.textPrimary, fontSize: 14, fontWeight: '900' },
  assignRetailerIntroText: { color: colors.textMuted, fontSize: 10, marginTop: 2 },
  retailerSearchActions: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  retailerComboOpen: {
    borderColor: colors.accentPrimary,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  retailerComboDropdown: {
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: colors.accentPrimary,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 13,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    ...shadows.soft,
  },
  retailerComboScroll: { maxHeight: 264 },
  retailerComboItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  retailerComboItemSelected: { backgroundColor: `${colors.accentPrimary}12` },
  retailerComboEmpty: {
    alignItems: 'center',
    gap: 10,
    paddingVertical: 18,
    paddingHorizontal: 12,
  },
  addRetailerButton: {
    width: 48,
    height: 48,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentPrimary,
  },
  productSearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    paddingVertical: 10,
  },
  scannerButton: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentPrimary,
  },
  searchHint: { color: colors.textMuted, fontSize: 10, marginTop: 5, marginBottom: 12 },
  productLoading: {
    minHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  productGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
    marginBottom: 14,
  },
  productCard: {
    width: '48.5%',
    minHeight: 230,
    padding: 11,
    borderRadius: 15,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  productCardDisabled: { opacity: 0.6 },
  productImageBox: {
    width: '100%',
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 9,
    borderRadius: 11,
    overflow: 'hidden',
    backgroundColor: colors.bgTertiary,
  },
  productImage: { width: '100%', height: '100%' },
  outOfStockOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15,23,42,0.52)',
  },
  outOfStockText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  imeiBadge: {
    position: 'absolute',
    top: 7,
    left: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 7,
    backgroundColor: colors.accentPrimary,
  },
  imeiBadgeText: { color: '#ffffff', fontSize: 8, fontWeight: '900' },
  productBrand: {
    color: colors.textMuted,
    fontSize: 8,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  productCardName: {
    minHeight: 36,
    color: colors.textPrimary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
  },
  productCardSku: { color: colors.textMuted, fontSize: 10, marginTop: 3 },
  productCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 5,
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  productCardPrice: { flex: 1, color: colors.accentPrimary, fontSize: 13, fontWeight: '900' },
  stockBadge: {
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: 'rgba(5,150,105,0.1)',
  },
  stockBadgeEmpty: { backgroundColor: 'rgba(225,29,72,0.1)' },
  stockBadgeText: { color: '#059669', fontSize: 8, fontWeight: '800' },
  stockBadgeTextEmpty: { color: '#e11d48' },
  productEmpty: {
    minHeight: 150,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  cartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    marginBottom: 8,
  },
  cartTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  cartTotal: { color: colors.accentPrimary, fontSize: 15, fontWeight: '900' },
  cartEmpty: {
    padding: 18,
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cartSerial: { color: colors.accentPrimary, fontSize: 9, fontFamily: 'monospace', marginTop: 3 },
  retailerCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 11,
    marginBottom: 7,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  retailerAvatar: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
  },
  retailerAvatarText: { color: colors.accentPrimary, fontSize: 15, fontWeight: '900' },
  selectedRetailerCard: {
    padding: 13,
    borderRadius: 15,
    backgroundColor: colors.accentSoft,
    borderWidth: 1.5,
    borderColor: colors.accentPrimary,
  },
  selectedRetailerTop: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  selectedRetailerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentPrimary,
  },
  selectedRetailerAvatarText: { color: '#ffffff', fontSize: 18, fontWeight: '900' },
  selectedRetailerNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 7,
  },
  assignedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 7,
    backgroundColor: 'rgba(5,150,105,0.1)',
  },
  assignedBadgeText: { color: '#059669', fontSize: 8, fontWeight: '900' },
  retailerBalanceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    padding: 10,
    borderRadius: 11,
    backgroundColor: '#ffffff',
  },
  retailerBalanceItem: { flex: 1, alignItems: 'center' },
  retailerBalanceDivider: { width: 1, height: 32, backgroundColor: colors.borderLight },
  retailerBalanceLabel: {
    color: colors.textMuted,
    fontSize: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  retailerBalanceValue: { fontSize: 13, fontWeight: '900', marginTop: 3 },
  retailerLoadingState: { minHeight: 160, alignItems: 'center', justifyContent: 'center', gap: 8 },
  retailerEmptyState: {
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    borderRadius: 14,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  addRetailerEmptyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginTop: 13,
    borderRadius: 11,
    backgroundColor: colors.accentPrimary,
  },
  addRetailerEmptyText: { color: '#ffffff', fontSize: 11, fontWeight: '900' },
  addRetailerHeading: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  addRetailerHeadingIcon: {
    width: 44,
    height: 44,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
  },
  addRetailerContent: { padding: 15, paddingBottom: 120 },
  addRetailerField: { marginBottom: 13 },
  addRetailerLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    fontWeight: '800',
    marginBottom: 6,
  },
  addRetailerInputWrap: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 11,
    borderRadius: 13,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  addRetailerInputMultiline: { minHeight: 96, alignItems: 'flex-start' },
  addRetailerFieldIcon: {
    width: 28,
    height: 28,
    marginTop: 1,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
  },
  addRetailerInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    paddingVertical: 10,
  },
  addRetailerTextArea: { minHeight: 90, textAlignVertical: 'top', paddingTop: 11 },
  addRetailerError: {
    padding: 11,
    borderRadius: 11,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  cartSummary: {
    marginTop: 16,
    padding: 13,
    borderRadius: 14,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingVertical: 6,
  },
  summaryName: { flex: 1, color: colors.textPrimary, fontSize: 12, fontWeight: '700' },
  summaryAmount: { color: colors.textMuted, fontSize: 11, fontWeight: '600' },
  summaryTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 7,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  footerActions: { flexDirection: 'row', alignItems: 'center', gap: 9 },
  backStepButton: {
    height: 47,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingHorizontal: 15,
    borderRadius: 13,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  backStepText: { color: colors.textPrimary, fontSize: 12, fontWeight: '800' },
  loadMoreButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 42,
    marginTop: 8,
    marginBottom: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: '#ffffff',
  },
  loadMoreText: {
    color: colors.accentPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  todayOrderBanner: {
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
  },
  todayOrderText: {
    color: '#1d4ed8',
    fontSize: 12,
    lineHeight: 17,
  },
  employeeLocked: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  tcNoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  selectedBox: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    marginBottom: 8,
  },
  selectedName: { color: colors.textPrimary, fontWeight: '800', fontSize: 14 },
  selectedMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  link: { color: colors.accentPrimary, fontWeight: '800', fontSize: 12, marginTop: 6 },
  pickRow: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pickRowOn: { borderColor: colors.accentPrimary, backgroundColor: colors.accentSoft },
  pickName: { color: colors.textPrimary, fontWeight: '700', fontSize: 13 },
  pickMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  pickPrice: { color: colors.accentPrimary, fontWeight: '900', fontSize: 13 },
  cartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: 7,
  },
  priceMini: {
    width: 72,
    height: 36,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingHorizontal: 8,
    color: colors.textPrimary,
    fontWeight: '700',
    backgroundColor: colors.bgTertiary,
  },
  qtyBtns: { flexDirection: 'row', gap: 6 },
  qtyBtnText: {
    width: 28,
    height: 28,
    textAlign: 'center',
    lineHeight: 26,
    borderRadius: 8,
    backgroundColor: colors.bgTertiary,
    color: colors.textPrimary,
    fontWeight: '800',
    overflow: 'hidden',
  },
  stepOneFooter: { gap: 10 },
  cartFooterButton: {
    minHeight: 60,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cartFooterLeft: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 10 },
  cartFooterIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  cartCountBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    minWidth: 19,
    height: 19,
    paddingHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.statusError,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  cartCountText: { color: '#ffffff', fontSize: 8, fontWeight: '900' },
  cartFooterTitle: { color: colors.textPrimary, fontSize: 12, fontWeight: '800' },
  cartFooterHint: { color: colors.textMuted, fontSize: 9, marginTop: 2 },
  cartFooterTotal: { color: colors.accentPrimary, fontSize: 16, fontWeight: '900' },
  cartDrawerOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15,23,42,0.62)',
  },
  cartDrawer: {
    maxHeight: '88%',
    minHeight: '55%',
    overflow: 'hidden',
    backgroundColor: colors.bgPrimary,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
  },
  cartDrawerHandle: {
    width: 42,
    height: 5,
    alignSelf: 'center',
    marginTop: 9,
    borderRadius: 3,
    backgroundColor: '#cbd5e1',
  },
  cartDrawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 15,
    paddingTop: 12,
    paddingBottom: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  cartDrawerTitleRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  cartDrawerIcon: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  cartDrawerTitle: { color: colors.textPrimary, fontSize: 17, fontWeight: '900' },
  cartDrawerSub: { color: colors.textMuted, fontSize: 10, marginTop: 2 },
  cartDrawerScroll: { flexGrow: 0 },
  cartDrawerContent: { padding: 12, paddingBottom: 18 },
  cartDrawerEmpty: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
  },
  cartItemCard: {
    padding: 12,
    marginBottom: 9,
    borderRadius: 15,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cartItemHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  cartItemName: { color: colors.textPrimary, fontSize: 14, lineHeight: 19, fontWeight: '800' },
  cartItemVariant: { color: colors.textMuted, fontSize: 10, marginTop: 2 },
  cartRemoveButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  cartSerialBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 8,
    paddingHorizontal: 9,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: colors.accentSoft,
  },
  cartSerialText: {
    flex: 1,
    color: colors.accentPrimary,
    fontSize: 9,
    lineHeight: 14,
    fontFamily: 'monospace',
  },
  cartItemControls: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 10,
  },
  quantityControl: {
    height: 39,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 11,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.bgTertiary,
  },
  quantityButton: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonDisabled: { opacity: 0.4 },
  quantityValue: {
    minWidth: 34,
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  fixedQuantity: {
    height: 39,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 11,
    borderRadius: 11,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  fixedQuantityValue: { color: colors.textPrimary, fontSize: 13, fontWeight: '900' },
  fixedQuantityLabel: {
    color: colors.textMuted,
    fontSize: 8,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  cartPriceWrap: { flex: 1, maxWidth: 150 },
  cartPriceLabel: {
    color: colors.textMuted,
    fontSize: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  cartPriceInputWrap: {
    height: 39,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 9,
    borderRadius: 11,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cartCurrency: { color: colors.accentPrimary, fontSize: 13, fontWeight: '900' },
  cartPriceInput: {
    flex: 1,
    height: 38,
    paddingHorizontal: 5,
    paddingVertical: 0,
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  cartLineTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingTop: 9,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  cartLineFormula: { color: colors.textMuted, fontSize: 10 },
  cartLineTotal: { color: colors.accentPrimary, fontSize: 14, fontWeight: '900' },
  cartDrawerFooter: {
    padding: 14,
    paddingBottom: 26,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    gap: 11,
  },
  cartGrandTotalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  cartGrandTotalLabel: { color: colors.textPrimary, fontSize: 14, fontWeight: '900' },
  cartGrandTotalItems: { color: colors.textMuted, fontSize: 9, marginTop: 2 },
  cartGrandTotalValue: { color: colors.accentPrimary, fontSize: 20, fontWeight: '900' },
  modalFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 14,
    paddingBottom: 28,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  imeiModalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15,23,42,0.62)',
  },
  imeiModalSheet: {
    maxHeight: '88%',
    minHeight: 480,
    paddingHorizontal: 16,
    paddingBottom: 28,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: '#ffffff',
  },
  imeiModalHandle: {
    alignSelf: 'center',
    width: 42,
    height: 5,
    marginTop: 9,
    marginBottom: 12,
    borderRadius: 3,
    backgroundColor: '#cbd5e1',
  },
  imeiModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  imeiModalIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  imeiModalTitle: { color: colors.textPrimary, fontSize: 18, fontWeight: '900' },
  imeiModalSub: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  imeiSelectionSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    padding: 12,
    marginBottom: 10,
    borderRadius: 14,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  imeiSummaryValue: { color: colors.textPrimary, fontSize: 17, fontWeight: '900' },
  imeiSummaryLabel: {
    color: colors.textMuted,
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  imeiSummaryDivider: { width: 1, height: 34, backgroundColor: colors.borderLight },
  imeiSelectAll: {
    marginLeft: 'auto',
    paddingHorizontal: 11,
    paddingVertical: 8,
    borderRadius: 9,
    backgroundColor: colors.accentSoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  imeiSelectAllText: { color: colors.accentPrimary, fontSize: 10, fontWeight: '900' },
  imeiSearchBar: {
    minHeight: 46,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  imeiSearchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 13,
    paddingVertical: 9,
  },
  imeiScroll: {
    flexGrow: 0,
    minHeight: 180,
    maxHeight: 410,
    marginBottom: 12,
  },
  imeiScrollContent: { paddingBottom: 6, gap: 7 },
  imeiOption: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  imeiOptionSelected: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accentPrimary,
  },
  imeiCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
  },
  imeiCheckboxSelected: {
    backgroundColor: colors.accentPrimary,
    borderColor: colors.accentPrimary,
  },
  imeiNumber: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '800',
    fontFamily: 'monospace',
  },
  imeiNumberSelected: { color: colors.accentPrimary },
  imeiAvailableText: { color: '#059669', fontSize: 9, fontWeight: '700', marginTop: 2 },
  imeiEmpty: { minHeight: 180, alignItems: 'center', justifyContent: 'center', gap: 8 },
  imeiEmptyText: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  imeiModalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  imeiCancelButton: {
    height: 47,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    borderRadius: 13,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  imeiCancelText: { color: colors.textPrimary, fontSize: 12, fontWeight: '800' },
  overlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(15,23,42,0.55)',
  },
  sheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 16,
    paddingBottom: 28,
  },
  summaryBox: {
    marginTop: 10,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: colors.bgTertiary,
  },
  returnIconWrap: {
    alignSelf: 'center',
    width: 64,
    height: 64,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(217,119,6,0.12)',
    borderWidth: 2,
    borderColor: 'rgba(217,119,6,0.25)',
    marginBottom: 14,
  },
  returnAmountBox: {
    marginTop: 14,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    backgroundColor: 'rgba(217,119,6,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(217,119,6,0.22)',
  },
  dangerBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#d97706',
  },
  dangerBtnText: { color: '#ffffff', fontWeight: '800', fontSize: 14 },
  ghostBtn: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  ghostBtnText: { color: colors.textSecondary, fontWeight: '800', fontSize: 14 },
});
