import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '@/theme/tokens';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bgPrimary },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
    gap: 12,
  },
  errorText: { color: colors.statusError, fontWeight: '700', fontSize: 15, textAlign: 'center' },
  mutedCenter: { color: colors.textMuted, fontSize: 13, textAlign: 'center', lineHeight: 18 },

  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingBottom: 10,
    gap: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  topBarTitle: { flex: 1 },
  topBarEyebrow: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  topBarHeading: { color: '#fff', fontSize: 17, fontWeight: '800', marginTop: 2 },

  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: 120,
    gap: 14,
  },

  hero: {
    borderRadius: radius.lg,
    padding: spacing.md,
    overflow: 'hidden',
  },
  heroTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  heroInvoice: { color: '#fff', fontSize: 20, fontWeight: '900', letterSpacing: -0.3 },
  heroOrderNo: { color: 'rgba(255,255,255,0.78)', fontSize: 12, marginTop: 4, fontWeight: '600' },
  heroDate: { color: 'rgba(255,255,255,0.7)', fontSize: 11, marginTop: 2 },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  statusPillText: { color: '#fff', fontSize: 11, fontWeight: '800', textTransform: 'capitalize' },
  typeChip: {
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  typeChipText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  heroInvoiceBtn: {
    marginTop: 14,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  heroInvoiceBtnText: { color: '#fff', fontSize: 13, fontWeight: '800' },

  metrics: { flexDirection: 'row', gap: 8 },
  metricCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: radius.md,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  metricLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  metricValue: { marginTop: 4, fontSize: 14, fontWeight: '800', color: colors.textPrimary },

  section: {
    backgroundColor: '#fff',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    padding: spacing.md,
  },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: '800' },
  sectionCount: {
    minWidth: 22,
    height: 22,
    paddingHorizontal: 6,
    borderRadius: 11,
    backgroundColor: colors.accentSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionCountText: { color: colors.accentPrimary, fontSize: 11, fontWeight: '800' },

  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 7,
    gap: 12,
  },
  infoLabel: { color: colors.textMuted, fontSize: 12, fontWeight: '600' },
  infoValue: {
    flex: 1,
    textAlign: 'right',
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  divider: { height: 1, backgroundColor: colors.borderLight, marginVertical: 4 },

  itemCard: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  itemCardLast: { borderBottomWidth: 0, paddingBottom: 0 },
  itemTop: { flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  itemName: { flex: 1, color: colors.textPrimary, fontSize: 14, fontWeight: '700' },
  itemTotal: { color: colors.accentPrimary, fontSize: 14, fontWeight: '800' },
  itemMeta: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  serials: { color: '#0369a1', fontSize: 11, marginTop: 4, fontWeight: '600' },

  summaryLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
  },
  summaryLabel: { color: colors.textMuted, fontSize: 13 },
  summaryValue: { color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  summaryGrand: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    marginTop: 6,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  summaryGrandLabel: { color: colors.textPrimary, fontSize: 15, fontWeight: '800' },
  summaryGrandValue: { color: colors.accentPrimary, fontSize: 16, fontWeight: '900' },

  timelineItem: { flexDirection: 'row', gap: 12, paddingVertical: 10 },
  timelineDotCol: { alignItems: 'center', width: 16 },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.accentPrimary,
    marginTop: 4,
  },
  timelineLine: { flex: 1, width: 2, backgroundColor: '#e0e7ff', marginTop: 4 },
  timelineBody: { flex: 1 },
  timelineAmount: { color: colors.statusSuccess, fontSize: 14, fontWeight: '800' },
  timelineMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },

  emptyPayments: { color: colors.textMuted, fontSize: 13, textAlign: 'center', paddingVertical: 8 },

  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacing.md,
    paddingTop: 12,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    flexDirection: 'row',
    gap: 10,
  },
  footerBtn: { flex: 1 },

  // —— Sales history list (matches Quick Sell / Wholesale premium shell) ——
  listRoot: { flex: 1, backgroundColor: colors.bgPrimary },
  shListContent: { paddingBottom: 130 },
  shHero: {
    margin: spacing.sm,
    borderRadius: radius.xl,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  shHeroIcon: {
    width: 50,
    height: 50,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  shHeroTitle: { color: '#ffffff', fontSize: 23, fontWeight: '900', letterSpacing: -0.4 },
  shHeroSub: { color: 'rgba(255,255,255,0.78)', fontSize: 11.5, marginTop: 3 },
  shHeroBadge: {
    minWidth: 44,
    height: 44,
    paddingHorizontal: 10,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  shHeroBadgeText: { color: '#4f46e5', fontWeight: '900', fontSize: 15 },

  shStatsRow: { flexDirection: 'row', gap: 8, paddingHorizontal: spacing.sm, marginBottom: 4 },
  shStatCard: {
    flex: 1,
    borderRadius: radius.md,
    padding: 11,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  shStatValue: { color: colors.textPrimary, fontSize: 16, fontWeight: '900' },
  shStatLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  shStatDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 7 },

  shSearchRow: {
    marginHorizontal: spacing.sm,
    marginTop: 8,
    marginBottom: 8,
    minHeight: 48,
    paddingHorizontal: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  shSearchInput: { flex: 1, color: colors.textPrimary, fontSize: 13, paddingVertical: 10 },

  shFilterRow: {
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: spacing.sm,
    marginBottom: 8,
    alignItems: 'center',
  },
  shFilterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    maxWidth: 150,
  },
  shFilterChipOn: { backgroundColor: colors.accentSoft, borderColor: colors.borderAccent },
  shFilterChipText: { color: colors.textMuted, fontWeight: '700', fontSize: 11 },
  shFilterChipTextOn: { color: colors.accentPrimary },

  shDateRow: {
    marginHorizontal: spacing.sm,
    marginBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  shDateRowDisabled: { opacity: 0.55 },
  shDateField: { flex: 1, minWidth: 0 },
  shDateLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  shDateInput: { color: colors.textPrimary, fontSize: 13, fontWeight: '700', paddingVertical: 0 },
  shDateSep: { color: colors.textMuted, fontWeight: '700' },
  shHint: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '600',
    marginHorizontal: spacing.sm,
    marginBottom: 8,
  },

  shCard: {
    backgroundColor: '#ffffff',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderLeftWidth: 4,
    padding: 13,
    marginHorizontal: spacing.sm,
    marginBottom: 10,
  },
  shCardTop: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  shCardIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  shCardBody: { flex: 1, minWidth: 0 },
  shCardInvoice: {
    color: colors.textPrimary,
    fontWeight: '800',
    fontSize: 15,
    letterSpacing: -0.2,
  },
  shCardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 3,
    flexWrap: 'wrap',
  },
  shCardMeta: { color: colors.textMuted, fontSize: 11, fontWeight: '600', maxWidth: 140 },
  shCardDot: { color: colors.textMuted, fontSize: 11 },
  shStatusPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  shStatusText: { fontSize: 10, fontWeight: '800', textTransform: 'capitalize' },
  shCardBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.bgTertiary,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  shTypePill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  shTypeText: { fontSize: 10, fontWeight: '800' },
  shAmounts: { flex: 1, alignItems: 'flex-end' },
  shTotal: { color: colors.textPrimary, fontSize: 15, fontWeight: '900' },
  shDue: { color: colors.statusWarning, fontSize: 11, fontWeight: '700', marginTop: 1 },
  shPaidHint: { color: colors.statusSuccess, fontSize: 11, fontWeight: '700', marginTop: 1 },

  shEmpty: { alignItems: 'center', padding: 42 },
  shEmptyTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: '800', marginTop: 12 },
  shEmptyText: { color: colors.textMuted, fontSize: 12, marginTop: 4, textAlign: 'center' },
  shFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
  },
  shFooterHint: { color: colors.textMuted, fontSize: 11, fontWeight: '600' },
  shPickerHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#cbd5e1',
    marginBottom: 12,
  },

  // legacy list keys kept for any leftover refs
  listHeader: { paddingHorizontal: spacing.md, paddingTop: spacing.md, paddingBottom: 8 },
  listTitle: { color: colors.textPrimary, fontSize: 22, fontWeight: '900', letterSpacing: -0.4 },
  listSub: { color: colors.textMuted, fontSize: 13, marginTop: 4 },
  listContent: { paddingHorizontal: spacing.md, paddingBottom: 100, gap: 10 },
  listCard: {
    backgroundColor: '#fff',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.borderLight,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  listCardBody: { flex: 1, minWidth: 0 },
  listInvoice: { color: colors.textPrimary, fontSize: 15, fontWeight: '800' },
  listMeta: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
  listRight: { alignItems: 'flex-end', gap: 4 },
  listTotal: { color: colors.textPrimary, fontSize: 15, fontWeight: '900' },
  listStatus: { fontSize: 11, fontWeight: '800', textTransform: 'capitalize' },
  listType: {
    alignSelf: 'flex-start',
    marginTop: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: colors.bgTertiary,
  },
  listTypeText: { color: colors.textSecondary, fontSize: 10, fontWeight: '700' },
  listEmpty: { color: colors.textMuted, textAlign: 'center', marginTop: 48, fontSize: 14 },
  searchWrap: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 0,
  },
  filterChips: { gap: 8, paddingTop: 12, paddingBottom: 4, paddingRight: 8 },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    maxWidth: 160,
  },
  filterChipOn: { borderColor: colors.accentPrimary, backgroundColor: colors.accentSoft },
  filterChipText: { color: colors.textPrimary, fontSize: 12, fontWeight: '700' },
  dateRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.md,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  dateRowDisabled: { opacity: 0.55 },
  dateField: { flex: 1, minWidth: 0 },
  dateLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  dateInput: { color: colors.textPrimary, fontSize: 13, fontWeight: '700', paddingVertical: 0 },
  dateSep: { color: colors.textMuted, fontWeight: '700' },
  searchHint: { color: colors.textMuted, fontSize: 11, marginTop: 8, marginBottom: 4 },

  // Pay due sheet
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.5)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    maxHeight: '88%',
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#cbd5e1',
    marginBottom: 12,
  },
  sheetTitle: { color: colors.textPrimary, fontSize: 18, fontWeight: '900' },
  sheetSub: { color: colors.textMuted, fontSize: 13, marginTop: 4, marginBottom: 14 },
  fieldLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
    marginTop: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 12,
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: '600',
    backgroundColor: colors.bgPrimary,
  },
  accountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: colors.bgPrimary,
  },
  accountName: { color: colors.textPrimary, fontSize: 14, fontWeight: '700' },
  accountHint: { color: colors.textMuted, fontSize: 12 },
  sheetActions: { flexDirection: 'row', gap: 10, marginTop: 18 },
  pickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.45)',
    justifyContent: 'flex-end',
  },
  pickerSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    padding: spacing.md,
    maxHeight: 420,
  },
  pickerTitle: { fontSize: 16, fontWeight: '800', color: colors.textPrimary, marginBottom: 10 },
  pickerItem: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    marginBottom: 8,
  },
  pickerItemOn: { borderColor: colors.accentPrimary, backgroundColor: colors.accentSoft },
});
